amcl:
  ros__parameters:
    use_sim_time: True
    
    # Frame settings
    global_frame_id: "map"
    odom_frame_id: "odom"
    base_frame_id: "base_link"
    
    # Transform settings - CRITICAL
    tf_broadcast: true
    transform_tolerance: 2.0  # Increased from 1.0
    
    # Initial pose
    set_initial_pose: true
    initial_pose:
      x: 0.0
      y: 0.0
      z: 0.0
      yaw: 0.0
    
    # Particle filter - make more robust
    min_particles: 500
    max_particles: 5000  # Increased
    
    # Recovery settings - make more aggressive
    recovery_alpha_slow: 0.001
    recovery_alpha_fast: 0.1
    
    # Update thresholds - less sensitive
    update_min_d: 0.2    # Increased - update if moved 20cm (less frequent)
    update_min_a: 0.2    # Increased - update if rotated 0.2rad (less frequent)
    
    # Motion model - make more forgiving
    alpha1: 0.2  # Expected noise in odometry rotation estimate from rotation
    alpha2: 0.2  # Expected noise in odometry rotation estimate from translation
    alpha3: 0.2  # Expected noise in odometry translation estimate from translation
    alpha4: 0.2  # Expected noise in odometry translation estimate from rotation
    alpha5: 0.2  # Translation noise
    
    # Laser model - more forgiving
    laser_likelihood_max_dist: 2.0  # Increased
    laser_max_beams: 30  # Reduced from default for performance
    laser_model_type: "likelihood_field"
    
    # Resample settings
    resample_interval: 2  # Increased - resample less frequently
    
    # Debug params
    save_pose_rate: 0.5

map_server:
  ros__parameters:
    use_sim_time: True
    yaml_filename: "map/map.yaml"

lifecycle_manager_localization:
  ros__parameters:
    use_sim_time: True
    autostart: True
    node_names: ["map_server", "amcl"]