version: '3.3'

services:
  # Serviço de Localização (AMCL + EKF)
  localization:
    build: 
      context: .
      dockerfile: Dockerfile
    stdin_open: true
    tty: true
    network_mode: host
    ipc: host
    privileged: true
    container_name: nav2_localization
    volumes:
      - ./cyclonedds.xml:/cyclonedds.xml:ro
      - /tmp/.X11-unix:/tmp/.X11-unix:rw
    environment:
      - ROS_DOMAIN_ID=30
      - CYCLONEDDS_URI=file:///cyclonedds.xml
      - DISPLAY=${DISPLAY}
      - RMW_IMPLEMENTATION=rmw_cyclonedx_cpp
    command: >
      bash -c "
      source /opt/ros/foxy/setup.bash &&
      source /workspace/install/setup.bash &&
      sleep 5 &&
      ros2 launch rm_localization localization.launch.py"
    restart: unless-stopped

  # Serviço de Navegação (Nav2 Stack)
  navigation:
    build: 
      context: .
      dockerfile: Dockerfile
    stdin_open: true
    tty: true
    network_mode: host
    ipc: host
    privileged: true
    container_name: nav2_navigation
    volumes:
      - ./cyclonedds.xml:/cyclonedds.xml:ro
      - /tmp/.X11-unix:/tmp/.X11-unix:rw
    environment:
      - ROS_DOMAIN_ID=30
      - CYCLONEDDS_URI=file:///cyclonedds.xml
      - DISPLAY=${DISPLAY}
      - RMW_IMPLEMENTATION=rmw_cyclonedx_cpp
    command: >
      bash -c "
      source /opt/ros/foxy/setup.bash &&
      source /workspace/install/setup.bash &&
      sleep 15 &&
      ros2 launch rm_navigation navigation.launch.py"
    depends_on:
      - localization
    restart: unless-stopped

  # Serviço do Publicador de Waypoints
  waypoint_follower:
    build: 
      context: .
      dockerfile: Dockerfile
    stdin_open: true
    tty: true
    network_mode: host
    ipc: host
    privileged: true
    container_name: nav2_waypoint_follower
    volumes:
      - ./cyclonedds.xml:/cyclonedds.xml:ro
      - /tmp/.X11-unix:/tmp/.X11-unix:rw
    environment:
      - ROS_DOMAIN_ID=30
      - CYCLONEDDS_URI=file:///cyclonedds.xml
      - DISPLAY=${DISPLAY}
      - RMW_IMPLEMENTATION=rmw_cyclonedx_cpp
    command: >
      bash -c "
      source /opt/ros/foxy/setup.bash &&
      source /workspace/install/setup.bash &&
      sleep 25 &&
      echo 'Waypoint service ready!' &&
      echo 'Call: ros2 service call /start_waypoint_navigation std_srvs/srv/Trigger' &&
      ros2 run waypoint_navigation_pkg waypoint_publisher"
    depends_on:
      - navigation
    restart: unless-stopped

# Volumes para logs
volumes:
  ros2_logs:
    driver: local