slam_toolbox:
  ros__parameters:
    # Robot frames and topics
    odom_frame: odom
    map_frame: map
    base_frame: base_link
    scan_topic: /scan

    # Mapping mode
    mode: mapping

    # Transform Configuration
    publish_tf: true
    tf_buffer_duration: 30.0
    tf_broadcast_period: 0.05
    transform_timeout: 0.2
    transform_publish_period: 0.02
    transform_tolerance: 0.1
    use_sim_time: true

    # Online synchronous
    use_pose_extrapolator: true
    pose_update_rate: 30.0
    map_update_interval: 5.0
    resolution: 0.05
    max_laser_range: 20.0
    minimum_time_interval: 0.5
    stack_size_to_use: 40000000
    enable_interactive_mode: true

    # Loop closure parameters
    loop_search_space: 8.0
    loop_match_minimum_chain_size: 3
    loop_match_maximum_variance_covariance: 3.0
    loop_match_minimum_response_coarse: 0.35
    loop_match_minimum_response_fine: 0.45

    # Scan matching parameters
    use_scan_matching: true
    use_scan_barycenter: true
    minimum_travel_distance: 0.5
    minimum_travel_heading: 0.5
    scan_buffer_size: 10
    scan_buffer_maximum_scan_distance: 10.0